"""baseline: track existing schema

Revision ID: 5d4221da5df3
Revises: 
Create Date: 2026-07-24 19:28:21.403490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d4221da5df3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_securite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_securite_produit_id'))

    op.drop_table('stock_securite')
    op.drop_table('stock_modifications')
    op.drop_table('stocks')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('points_fidelite',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('fournisseurs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fournisseurs_groupe_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'groupes_fournisseurs', ['groupe_id'], ['id'])

    with op.batch_alter_table('groupes_clients', schema=None) as batch_op:
        batch_op.alter_column('pourcentage_absorption',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('stock_entries', schema=None) as batch_op:
        batch_op.alter_column('qr_tire',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_foreign_key(None, 'commande_lignes', ['commande_ligne_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('stock_exit_logs', schema=None) as batch_op:
        batch_op.alter_column('prix_unite_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_sous_unite_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_sous_sous_unite_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_unite_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_sous_unite_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_sous_sous_unite_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('tva_pourcentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_sortie_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_sortie_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('stock_modification_logs', schema=None) as batch_op:
        batch_op.alter_column('old_qr_tire',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('new_qr_tire',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('vente_lignes', schema=None) as batch_op:
        batch_op.alter_column('numero_vente',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('stock_unite_avant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('stock_sous_unite_avant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('stock_sous_sous_unite_avant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_vente_lignes_numero_vente'), ['numero_vente'], unique=False)

    with op.batch_alter_table('ventes', schema=None) as batch_op:
        batch_op.alter_column('montant_recu',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('montant_hors_solde',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('montant_solde_client',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('montant_solde_groupe',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('monnaie_rendue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('solde_client_avant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('solde_client_apres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('solde_groupe_avant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('solde_groupe_apres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('points_gagnes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('points_totaux_apres',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('code_promo_montant_deduit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('points_client_apres')
        batch_op.drop_column('points_client_avant')
        batch_op.drop_column('points_utilises')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_utilises', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('points_client_avant', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('points_client_apres', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.alter_column('code_promo_montant_deduit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('points_totaux_apres',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('points_gagnes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('solde_groupe_apres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('solde_groupe_avant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('solde_client_apres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('solde_client_avant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('monnaie_rendue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('montant_solde_groupe',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('montant_solde_client',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('montant_hors_solde',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('montant_recu',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('vente_lignes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vente_lignes_numero_vente'))
        batch_op.alter_column('stock_sous_sous_unite_avant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('stock_sous_unite_avant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('stock_unite_avant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('numero_vente',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('stock_modification_logs', schema=None) as batch_op:
        batch_op.alter_column('new_qr_tire',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('old_qr_tire',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('stock_exit_logs', schema=None) as batch_op:
        batch_op.alter_column('total_sortie_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_sortie_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('tva_pourcentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_sous_sous_unite_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_sous_unite_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_unite_ttc',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_sous_sous_unite_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_sous_unite_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('prix_unite_ht',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('stock_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('qr_tire',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('groupes_clients', schema=None) as batch_op:
        batch_op.alter_column('pourcentage_absorption',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('fournisseurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fournisseurs_groupe_id_fkey'), 'groupes_fournisseurs', ['groupe_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('points_fidelite',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    op.create_table('stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantite_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantite_sous_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantite_sous_sous_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], name=op.f('stocks_produit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stocks_pkey')),
    sa.UniqueConstraint('produit_id', name=op.f('stocks_produit_id_key'))
    )
    op.create_table('stock_modifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('produit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('old_quantite_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_quantite_sous_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_quantite_sous_sous_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_quantite_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_quantite_sous_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_quantite_sous_sous_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('numero_bl', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('date_peremption', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('code_suivi', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], name=op.f('stock_modifications_produit_id_fkey')),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('stock_modifications_stock_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('stock_modifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_modifications_pkey'))
    )
    op.create_table('stock_securite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seuil_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seuil_sous_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seuil_sous_sous_unites', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], name=op.f('stock_securite_produit_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('stock_securite_updated_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_securite_pkey'))
    )
    with op.batch_alter_table('stock_securite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_securite_produit_id'), ['produit_id'], unique=True)

    # ### end Alembic commands ###
