# -*- coding: utf-8 -*-
"""Référentiel des monnaies du monde (ISO 4217) et helpers de la devise active.

La devise choisie est stockée dans Setting (clé 'currency_code'). Le symbole est
injecté dans tous les templates via un context processor (variable `devise`),
et les générateurs PDF/Excel/messages Python passent par devise_active().
"""

# (code ISO, nom français, symbole affiché)
CURRENCIES = [
    ('AED', 'Dirham des Émirats arabes unis', 'د.إ'),
    ('AFN', 'Afghani afghan', '؋'),
    ('ALL', 'Lek albanais', 'L'),
    ('AMD', 'Dram arménien', '֏'),
    ('ANG', 'Florin antillais', 'ƒ'),
    ('AOA', 'Kwanza angolais', 'Kz'),
    ('ARS', 'Peso argentin', '$'),
    ('AUD', 'Dollar australien', 'A$'),
    ('AWG', 'Florin arubais', 'ƒ'),
    ('AZN', 'Manat azerbaïdjanais', '₼'),
    ('BAM', 'Mark convertible de Bosnie-Herzégovine', 'KM'),
    ('BBD', 'Dollar barbadien', 'Bds$'),
    ('BDT', 'Taka bangladais', '৳'),
    ('BGN', 'Lev bulgare', 'лв'),
    ('BHD', 'Dinar bahreïni', '.د.ب'),
    ('BIF', 'Franc burundais', 'FBu'),
    ('BMD', 'Dollar bermudien', 'BD$'),
    ('BND', 'Dollar de Brunei', 'B$'),
    ('BOB', 'Boliviano bolivien', 'Bs.'),
    ('BRL', 'Réal brésilien', 'R$'),
    ('BSD', 'Dollar bahaméen', 'B$'),
    ('BTN', 'Ngultrum bhoutanais', 'Nu.'),
    ('BWP', 'Pula botswanais', 'P'),
    ('BYN', 'Rouble biélorusse', 'Br'),
    ('BZD', 'Dollar bélizien', 'BZ$'),
    ('CAD', 'Dollar canadien', 'C$'),
    ('CDF', 'Franc congolais', 'FC'),
    ('CHF', 'Franc suisse', 'CHF'),
    ('CLP', 'Peso chilien', 'CLP$'),
    ('CNY', 'Yuan renminbi chinois', '¥'),
    ('COP', 'Peso colombien', 'COL$'),
    ('CRC', 'Colón costaricien', '₡'),
    ('CUP', 'Peso cubain', '₱'),
    ('CVE', 'Escudo cap-verdien', 'CVE'),
    ('CZK', 'Couronne tchèque', 'Kč'),
    ('DJF', 'Franc djiboutien', 'Fdj'),
    ('DKK', 'Couronne danoise', 'kr'),
    ('DOP', 'Peso dominicain', 'RD$'),
    ('DZD', 'Dinar algérien', 'دج'),
    ('EGP', 'Livre égyptienne', 'E£'),
    ('ERN', 'Nakfa érythréen', 'Nfk'),
    ('ETB', 'Birr éthiopien', 'Br'),
    ('EUR', 'Euro', '€'),
    ('FJD', 'Dollar fidjien', 'FJ$'),
    ('GBP', 'Livre sterling', '£'),
    ('GEL', 'Lari géorgien', '₾'),
    ('GHS', 'Cedi ghanéen', 'GH₵'),
    ('GMD', 'Dalasi gambien', 'D'),
    ('GNF', 'Franc guinéen', 'FG'),
    ('GTQ', 'Quetzal guatémaltèque', 'Q'),
    ('GYD', 'Dollar guyanien', 'G$'),
    ('HKD', 'Dollar de Hong Kong', 'HK$'),
    ('HNL', 'Lempira hondurien', 'L'),
    ('HTG', 'Gourde haïtienne', 'G'),
    ('HUF', 'Forint hongrois', 'Ft'),
    ('IDR', 'Roupie indonésienne', 'Rp'),
    ('ILS', 'Shekel israélien', '₪'),
    ('INR', 'Roupie indienne', '₹'),
    ('IQD', 'Dinar irakien', 'ع.د'),
    ('IRR', 'Rial iranien', '﷼'),
    ('ISK', 'Couronne islandaise', 'kr'),
    ('JMD', 'Dollar jamaïcain', 'J$'),
    ('JOD', 'Dinar jordanien', 'JD'),
    ('JPY', 'Yen japonais', '¥'),
    ('KES', 'Shilling kényan', 'KSh'),
    ('KGS', 'Som kirghize', 'сом'),
    ('KHR', 'Riel cambodgien', '៛'),
    ('KMF', 'Franc comorien', 'CF'),
    ('KPW', 'Won nord-coréen', '₩'),
    ('KRW', 'Won sud-coréen', '₩'),
    ('KWD', 'Dinar koweïtien', 'KD'),
    ('KYD', 'Dollar des îles Caïmans', 'CI$'),
    ('KZT', 'Tenge kazakh', '₸'),
    ('LAK', 'Kip laotien', '₭'),
    ('LBP', 'Livre libanaise', 'ل.ل'),
    ('LKR', 'Roupie srilankaise', 'Rs'),
    ('LRD', 'Dollar libérien', 'L$'),
    ('LSL', 'Loti lesothan', 'L'),
    ('LYD', 'Dinar libyen', 'LD'),
    ('MAD', 'Dirham marocain', 'DH'),
    ('MDL', 'Leu moldave', 'L'),
    ('MGA', 'Ariary malgache', 'Ar'),
    ('MKD', 'Denar macédonien', 'ден'),
    ('MMK', 'Kyat birman', 'K'),
    ('MNT', 'Tugrik mongol', '₮'),
    ('MOP', 'Pataca macanaise', 'MOP$'),
    ('MRU', 'Ouguiya mauritanien', 'UM'),
    ('MUR', 'Roupie mauricienne', 'Rs'),
    ('MVR', 'Rufiyaa maldivienne', 'Rf'),
    ('MWK', 'Kwacha malawien', 'MK'),
    ('MXN', 'Peso mexicain', 'Mex$'),
    ('MYR', 'Ringgit malaisien', 'RM'),
    ('MZN', 'Metical mozambicain', 'MT'),
    ('NAD', 'Dollar namibien', 'N$'),
    ('NGN', 'Naira nigérian', '₦'),
    ('NIO', 'Córdoba nicaraguayen', 'C$'),
    ('NOK', 'Couronne norvégienne', 'kr'),
    ('NPR', 'Roupie népalaise', 'Rs'),
    ('NZD', 'Dollar néo-zélandais', 'NZ$'),
    ('OMR', 'Rial omanais', 'ر.ع.'),
    ('PAB', 'Balboa panaméen', 'B/.'),
    ('PEN', 'Sol péruvien', 'S/'),
    ('PGK', 'Kina papou-néo-guinéen', 'K'),
    ('PHP', 'Peso philippin', '₱'),
    ('PKR', 'Roupie pakistanaise', 'Rs'),
    ('PLN', 'Zloty polonais', 'zł'),
    ('PYG', 'Guarani paraguayen', '₲'),
    ('QAR', 'Riyal qatari', 'ر.ق'),
    ('RON', 'Leu roumain', 'lei'),
    ('RSD', 'Dinar serbe', 'дин'),
    ('RUB', 'Rouble russe', '₽'),
    ('RWF', 'Franc rwandais', 'FRw'),
    ('SAR', 'Riyal saoudien', 'ر.س'),
    ('SBD', 'Dollar des îles Salomon', 'SI$'),
    ('SCR', 'Roupie seychelloise', 'SR'),
    ('SDG', 'Livre soudanaise', 'ج.س'),
    ('SEK', 'Couronne suédoise', 'kr'),
    ('SGD', 'Dollar de Singapour', 'S$'),
    ('SHP', 'Livre de Sainte-Hélène', '£'),
    ('SLE', 'Leone sierra-léonais', 'Le'),
    ('SOS', 'Shilling somalien', 'Sh.So.'),
    ('SRD', 'Dollar surinamais', 'SR$'),
    ('SSP', 'Livre sud-soudanaise', 'SS£'),
    ('STN', 'Dobra santoméen', 'Db'),
    ('SYP', 'Livre syrienne', 'S£'),
    ('SZL', 'Lilangeni swazi', 'E'),
    ('THB', 'Baht thaïlandais', '฿'),
    ('TJS', 'Somoni tadjik', 'SM'),
    ('TMT', 'Manat turkmène', 'm'),
    ('TND', 'Dinar tunisien', 'DT'),
    ('TOP', 'Paʻanga tongien', 'T$'),
    ('TRY', 'Livre turque', '₺'),
    ('TTD', 'Dollar trinidadien', 'TT$'),
    ('TWD', 'Dollar taïwanais', 'NT$'),
    ('TZS', 'Shilling tanzanien', 'TSh'),
    ('UAH', 'Hryvnia ukrainienne', '₴'),
    ('UGX', 'Shilling ougandais', 'USh'),
    ('USD', 'Dollar américain', '$'),
    ('UYU', 'Peso uruguayen', '$U'),
    ('UZS', 'Sum ouzbek', 'soʻm'),
    ('VES', 'Bolívar vénézuélien', 'Bs.'),
    ('VND', 'Dong vietnamien', '₫'),
    ('VUV', 'Vatu vanuatuan', 'VT'),
    ('WST', 'Tala samoan', 'WS$'),
    ('XAF', 'Franc CFA (Afrique centrale, BEAC)', 'FCFA'),
    ('XCD', 'Dollar des Caraïbes orientales', 'EC$'),
    ('XOF', 'Franc CFA (Afrique de l\'Ouest, BCEAO)', 'FCFA'),
    ('XPF', 'Franc pacifique (CFP)', 'F'),
    ('YER', 'Rial yéménite', '﷼'),
    ('ZAR', 'Rand sud-africain', 'R'),
    ('ZMW', 'Kwacha zambien', 'ZK'),
    ('ZWG', 'Zimbabwe Gold', 'ZiG'),
]

CURRENCIES_BY_CODE = {code: {'code': code, 'nom': nom, 'symbole': symbole} for code, nom, symbole in CURRENCIES}

DEFAULT_CURRENCY_CODE = 'EUR'


def get_active_currency():
    """Devise active de la pharmacie (dict code/nom/symbole), EUR par défaut.
    À appeler dans un contexte applicatif (requête, outil IA, export...)."""
    from models.setting import Setting
    code = (Setting.get_value('currency_code', DEFAULT_CURRENCY_CODE) or DEFAULT_CURRENCY_CODE).upper()
    return CURRENCIES_BY_CODE.get(code, CURRENCIES_BY_CODE[DEFAULT_CURRENCY_CODE])


def devise_active():
    """Symbole de la devise active (raccourci pour les f-strings Python)."""
    return get_active_currency()['symbole']
